// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types.js';

const SUPABASE_URL = "https://fijhelddrjtmuiztmwau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpamhlbGRkcmp0bXVpenRtd2F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3NDg4OTMsImV4cCI6MjA4NzMyNDg5M30.NzCk6tv-e40EguExveQM2Grx-SA4Rt-B7WdnBm5pc6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});