// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbnbififhmiqwexebzuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJibmJpZmlmaG1pcXdleGVienV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMTM3NzQsImV4cCI6MjA3MzY4OTc3NH0.9rPrkYwEbr_8C97B8QrKW5G5fcvHaqMbUJFQYfjwQHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});