
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types.js';

// WARNING: Do not hardcode sensitive keys. Use environment variables instead.
// Support both Vite (import.meta.env) and Node (process.env) for env vars
const SUPABASE_URL = typeof window === 'undefined'
  ? process.env.NEXT_PUBLIC_SUPABASE_URL || "https://rbnbififhmiqwexebzuw.supabase.co"
  : import.meta.env.VITE_SUPABASE_URL || "https://rbnbififhmiqwexebzuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = typeof window === 'undefined'
  ? process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || ""
  : import.meta.env.VITE_SUPABASE_ANON_KEY || "";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
